urls:
  api: 'https://devnet-api.multiversx.com'
  swagger:
    - 'http://localhost:3000'
    - 'https://devnet-microservice.multiversx.com'
    - 'https://testnet-microservice.multiversx.com'
    - 'https://microservice.multiversx.com'
  redis: '127.0.0.1'
database:
  host: 'localhost'
  port: 27017
  username: ''
  password: ''
  name: 'dev'
  enabled: false
features:
  publicApi:
    enabled: true
    port: 3000
  privateApi:
    enabled: true
    port: 4000
  cacheWarmer:
    enabled: true
    port: 5201
  transactionProcessor:
    enabled: false
    port: 5202
    maxLookBehind: 100
  queueWorker:
    enabled: false
    port: 8000
  keepAliveAgent:
    enabled: true
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - https://utils.multiversx.com
security:
  admins:
    - erd1u7jcj0mnszutju3hlr3ft998ul37z3zgvtsjmf82pkkx5cw53wjsqvhn6q
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
useCachingInterceptor: false
network: 'D'
addresses:
  ownerAddress: erd1u7jcj0mnszutju3hlr3ft998ul37z3zgvtsjmf82pkkx5cw53wjsqvhn6q
contracts:
  pulsarPage: erd1qqqqqqqqqqqqqpgqztlk8lnk03dfqukhcjfrk3tcymy98y693wjs5yy398
