// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    payment_links
    (
        init => init
        create => create_payment_link
        claim => claim_payment
        withdraw => withdraw_payment
        whitelistToken => whitelist_token_internal
        unwhitelistToken => unwhitelist_token_internal
        setFee => set_fee
        getFee => fee
        getMinimumDuration => get_minimum_duration
        getFeeAddress => fee_address
        getPaymentLinks => payment_links
        getWhitelistedTokensAndCollections => whitelisted_tokens_and_collections
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
