// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    transfer
    (
        init => init
        setFeePercentage => set_fee_percentage
        setFeeAddress => set_fee_address
        setNftIdentifier => set_nft_identifier
        addTokenToWhitelist => add_token_to_whitelist
        removeTokenFromWhitelist => remove_token_from_whitelist
        setNftPrice => set_nft_price
        setInitialPrices => set_initial_prices
        buyNft => buy_nft
        register => register
        transfer => transfer
        getFeePercentage => fee_percentage
        getFeeAddress => fee_address
        getWhitelistedTokens => whitelisted_tokens
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
